### ISSUE TITLE
Data Generation Step 00

### ISSUE THREAD

**Issue by sktalha68** [cshizhe/HM3DAutoVLN#5]
Hello.

Can you please guide me which version of habitat-sim are you using for generation of navigation graphs?

I have tried habitat-sim 0.3.1 and 0.2.1, but both give me issues.
```
with habitat-sim 0.3.1:

Traceback (most recent call last):
  File "/media/sheikh/f195cea0-aeff-4b97-870e-04f122355240/Projects/Active/HM3DAutoVLN/hm3d_data_gen/step00_orig.py", line 298, in <module>
    create_nav_graphs(args.output_dir) 
  File "/media/sheikh/f195cea0-aeff-4b97-870e-04f122355240/Projects/Active/HM3DAutoVLN/hm3d_data_gen/step00_orig.py", line 218, in create_nav_graphs
    sim_cfg = build_simulator_config(scene_id)
  File "/media/sheikh/f195cea0-aeff-4b97-870e-04f122355240/Projects/Active/HM3DAutoVLN/hm3d_data_gen/step00_orig.py", line 46, in build_simulator_config
    sensor_cfg.position = position
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: habitat_sim._ext.habitat_sim_bindings.SensorSpec, arg0: _magnum.Vector3) -> None

Invoked with: <habitat_sim._ext.habitat_sim_bindings.SensorSpec object at 0x7fc6063cde00>, [0, 1.5, 0]
```
```
with habitat-sim 0.2.1:

Traceback (most recent call last):
  File "step00_orig.py", line 298, in <module>
    create_nav_graphs(args.output_dir) 
  File "step00_orig.py", line 219, in create_nav_graphs
    sim = habitat_sim.Simulator(sim_cfg)
  File "<attrs generated init habitat_sim.simulator.Simulator>", line 11, in __init__
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/simulator.py", line 121, in __attrs_post_init__
    self.__set_from_config(self.config)
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/simulator.py", line 253, in __set_from_config
    self._config_agents(config)
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/simulator.py", line 204, in _config_agents
    for cfg in config.agents
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/simulator.py", line 204, in <listcomp>
    for cfg in config.agents
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/agent/agent.py", line 152, in __init__
    self.reconfigure(self.agent_config)
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/agent/agent.py", line 171, in reconfigure
    self._add_sensor(spec, modify_agent_config=False)
  File "/home/sheikh/anaconda3/envs/habitatold/lib/python3.6/site-packages/habitat_sim/agent/agent.py", line 187, in _add_sensor
    self._sensors.add(sensor_suite[spec.uuid])
KeyError: 'RGB'
```

**Comment by cshizhe** [comment]
Hi, I used habitat v1 at that time. The APIs have been significantly changed in habitat v2. Sorry I won't be able to update this codebase for that.
